spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumerGroup1
      enable-auto-commit: true
      auto-offset-reset: latest
      max-poll-records: 1000
    template:
      default-topic: kafkaTest
