### 회원가입1
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "박영재"
}

### 회원가입2
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "김대휘"
}

### 1번 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "123456"
}

### 2번 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": "123456"
}

### 방 만들기 > 게임방 멤버 정보 구독 + 세션 ID 저장용 SEND
POST http://localhost:8080/api/v1/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBuYXZlci5jb20iLCJpZCI6MSwibmlja25hbWUiOiLrsJXsmIHsnqwiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlhdCI6MTcwOTY5MjEwOSwiZXhwIjoxNzE5NjgzOTA5fQ.VD9y25LLgg_r7O0FFV19W0ot-B8OHA6fVyPFT6iu4RVw865k1cPfYPjDQR5x-Gqt20grmgUDYKx4x-yFbbdSuQ

{
  "title": "빙봉의 게임",
  "maxPlayer": 5,
  "round": 5,
  "password": "1234",
  "gameType": "WORD"
}

### 게임방 입장
POST http://localhost:8080/api/v1/rooms/1/enter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfR1VFU1QiLCJpZCI6MTAwMDYsIm5pY2tuYW1lIjoi7IaQ64uYMGI4OTAiLCJpYXQiOjE3MDg5NjExMTcsImV4cCI6MTcxODk1MjkxN30.yQCbkbLaGVeF8gplAp2m1oi0UWN4oKeL3TAxkktoxfJsTj4e88JJE_p9mB2wn1wBSs5OrmIDKTLIEC8Qml71MA

{
  "password": "1234"
}

### 게임방 수정
PATCH http://localhost:8080/api/v1/rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBuYXZlci5jb20iLCJuaWNrbmFtZSI6IuuwleyYgeyerCIsImlkIjoxLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlhdCI6MTcwODk1NjE5MCwiZXhwIjoxNzE4OTQ3OTkwfQ.4POsaCbUTgwlxXnZQFxzpqLrUe0T-Q7OFowFhdqXnshum_TdMyAfQSwLEfP1hx_9eSSIL4KIo7C9YAMV72HHyw

{
  "title": "11",
  "password": "123",
  "maxPlayer": 2,
  "round": 1,
  "gameType": "WORD"
}

###
POST http://localhost:8080/api/v1/auth/guest
