### 회원가입
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "빙봉"
}

### 회원가입2
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "장주영"
}

### 회원가입3
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "박영재"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "123456"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "123456"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": "123456"
}

<> 2024-02-08T215253.200.json
<> 2024-02-08T214523.200.json
<> 2024-02-08T214506.500.json

### 방 만들기 > 게임방 멤버 정보 구독 + 세션 ID 저장용 SEND
POST http://localhost:8080/api/v1/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwic3ViIjoidGVzdEBuYXZlci5jb20iLCJpYXQiOjE3MDc4Nzc0OTcsImV4cCI6MTcwNzg3OTI5Nywicm9sZXMiOiJST0xFX1VTRVIifQ.TyX7otXtcl_k15olP-l-E4jwrs6V-VzJeFhnjtuaddJjBnqwsafeYdJFx755zPoC

{
  "title": "빙봉의 게임",
  "maxPlayer": 2,
  "roundCount": 5,
  "gameType": "WORD"
}

### 게임방 입장
POST http://localhost:8080/api/v1/rooms/1/enter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6Miwic3ViIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA3ODc3NjE0LCJleHAiOjE3MDc4Nzk0MTQsInJvbGVzIjoiUk9MRV9VU0VSIn0.FIFtIac_cuBNoqPBI2yk8ywdA_9JHIf0AVxtk97mH4BkBqRcuI2nBYPDRLwbTpMk

### 조회
GET http://localhost:8081/api/v1/rooms?page=1&size=10
