### 회원가입1
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "박영재"
}

### 회원가입2
POST http://localhost:8080/api/v1/members/sign-up
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": "123456",
  "passwordConfirm": "123456",
  "nickname": "김대휘"
}

### 1번 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "123456"
}

### 2번 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": "123456"
}

### 방 만들기 > 게임방 멤버 정보 구독 + 세션 ID 저장용 SEND
POST http://localhost:8080/api/v1/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA4ODc4NjAxLCJleHAiOjE3MTg4NzA0MDEsInJvbGVzIjoiUk9MRV9VU0VSIn0.xsAXSOAx36bg0K6BIRbTSX30N9V7udP2ybo6LDR6dyGqAQHMjgDF7nCbPp0RNhaNHV057e09AEw_cb9_4wdGkA

{
  "title": "빙봉의 게임",
  "maxPlayer": 2,
  "round": 5,
  "password": "1234",
  "gameType": "SENTENCE"
}

### 게임방 입장
POST http://localhost:8080/api/v1/rooms/1/enter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6Miwic3ViIjoidGVzdDJAbmF2ZXIuY29tIiwiaWF0IjoxNzA4ODc4NjYwLCJleHAiOjE3MTg4NzA0NjAsInJvbGVzIjoiUk9MRV9VU0VSIn0.2WUjKqXzHxfmKVDcNsaTQO7fQC0oyFYldM8KhM3fd56dr4c5afLHOx2qApZX03lfe3tZkMtq7i0WPgiJOkAJ4g

{
  "password": "1234"
}

### 게임방 수정
PATCH http://localhost:8080/api/v1/rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA4NTIyMTQ2LCJleHAiOjE3MTg1MTM5NDYsInJvbGVzIjoiUk9MRV9VU0VSIn0.f72KiCAaiyoNzNRWuVPeETHEMSHoKknpJIm-tJn8BpLNMwJXIpQP96kaAWvww3CJSVO9OWRo_a1ZXt7aXU5y3Q

{
  "title": "11",
  "password": "123",
  "maxPlayer": 2,
  "round": 1,
  "gameType": "WORD"
}
