insert into member (created_at, updated_at, email, nickname, password, role, status)
values (NOW(), NOW(), 'test1@naver.com', '박영재', '{bcrypt}$2a$10$jSTH3yTOzqXr14LYOz.BJ.gCjCvDOeTKaNoJ2/qyxlFXB1ii7r8dC',
        'ROLE_USER', 'ACTIVE'),
       (NOW(), NOW(), 'test2@naver.com', '김대휘', '{bcrypt}$2a$10$jSTH3yTOzqXr14LYOz.BJ.gCjCvDOeTKaNoJ2/qyxlFXB1ii7r8dC',
        'ROLE_USER', 'ACTIVE');

INSERT INTO game_question (question, game_type)
VALUES ('리액트', 'WORD'),
       ('스프링', 'WORD'),
       ('코틀린', 'WORD'),
       ('자바', 'WORD'),
       ('파이썬', 'WORD'),
       ('노드', 'WORD'),
       ('익스프레스', 'WORD'),
       ('뷰', 'WORD'),
       ('앵귤러', 'WORD'),
       ('HTML', 'WORD'),
       ('CSS', 'WORD'),
       ('자바스크립트', 'WORD'),
       ('타입스크립트', 'WORD'),
       ('부트스트랩', 'WORD'),
       ('SASS', 'WORD'),
       ('레스', 'WORD'),
       ('웹팩', 'WORD'),
       ('바벨', 'WORD'),
       ('NPM', 'WORD'),
       ('YARN', 'WORD'),
       ('ESLint', 'WORD'),
       ('GIT', 'WORD'),
       ('깃허브', 'WORD'),
       ('비주얼코드', 'WORD'),
       ('인텔리제이', 'WORD'),
       ('이클립스', 'WORD'),
       ('안드로이드', 'WORD'),
       ('iOS', 'WORD'),
       ('코코아', 'WORD'),
       ('스위프트', 'WORD'),
       ('오브젝트C', 'WORD'),
       ('플러터', 'WORD'),
       ('다트', 'WORD'),
       ('코로나', 'WORD'),
       ('유니티', 'WORD'),
       ('언리얼', 'WORD'),
       ('C#', 'WORD'),
       ('C++', 'WORD'),
       ('루비', 'WORD'),
       ('PHP', 'WORD'),
       ('펄', 'WORD'),
       ('라라벨', 'WORD'),
       ('심포니', 'WORD'),
       ('케이크PHP', 'WORD'),
       ('스프링부트', 'WORD'),
       ('마이바티스', 'WORD'),
       ('하이버네이트', 'WORD'),
       ('JPA', 'WORD'),
       ('젠킨스', 'WORD'),
       ('도커', 'WORD'),
       ('쿠버네티스', 'WORD'),
       ('앤서블', 'WORD'),
       ('테라폼', 'WORD'),
       ('AWS', 'WORD'),
       ('GCP', 'WORD'),
       ('애저', 'WORD'),
       ('오라클', 'WORD'),
       ('SQL', 'WORD'),
       ('MySQL', 'WORD'),
       ('Redis', 'WORD'),
       ('인메모리캐시', 'WORD'),
       ('로그스태시', 'WORD'),
       ('키바나', 'WORD'),
       ('그라파나', 'WORD'),
       ('제이유닛', 'WORD'),
       ('셀레니움', 'WORD'),
       ('캐스퍼JS', 'WORD'),
       ('모카', 'WORD'),
       ('제스', 'WORD'),
       ('카르마', 'WORD'),
       ('프로트랙터', 'WORD'),
       ('스토리북', 'WORD'),
       ('사이프레스', 'WORD'),
       ('포스트맨', 'WORD'),
       ('스웨거', 'WORD'),
       ('아폴로', 'WORD'),
       ('그래프QL', 'WORD'),
       ('REST', 'WORD'),
       ('SOAP', 'WORD'),
       ('멀티쓰레드', 'WORD'),
       ('비동기', 'WORD'),
       ('프로미스', 'WORD'),
       ('옵저버블', 'WORD'),
       ('리덕스', 'WORD'),
       ('몹엑스', 'WORD'),
       ('컨텍스트', 'WORD'),
       ('훅', 'WORD'),
       ('클래스', 'WORD'),
       ('프로토타입', 'WORD'),
       ('이벤트루프', 'WORD'),
       ('웹소켓', 'WORD'),
       ('웹RTC', 'WORD'),
       ('SVG', 'WORD'),
       ('캔버스', 'WORD'),
       ('웹GL', 'WORD'),
       ('애니메이션', 'WORD'),
       ('트랜지션', 'WORD'),
       ('플렉스', 'WORD'),
       ('그리드', 'WORD'),
       ('반응형', 'WORD'),
       ('어댑티브', 'WORD'),
       ('SEO', 'WORD'),
       ('액세서빌리티', 'WORD'),
       ('i18n', 'WORD'),
       ('L10n', 'WORD'),
       ('퍼포먼스', 'WORD'),
       ('최적화', 'WORD'),
       ('메모리릭', 'WORD'),
       ('캐시', 'WORD'),
       ('로드밸런싱', 'WORD'),
       ('CDN', 'WORD'),
       ('SSL', 'WORD'),
       ('HTTPS', 'WORD'),
       ('도메인', 'WORD'),
       ('DNS', 'WORD'),
       ('라우팅', 'WORD'),
       ('미들웨어', 'WORD'),
       ('CORS', 'WORD'),
       ('JWT', 'WORD'),
       ('OAuth', 'WORD'),
       ('SAML', 'WORD');

INSERT INTO game_question (created_at, updated_at, question, game_type)
VALUES (NOW(), NOW(),
        'public class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello, World!");\n\t}\n}',
        'CODE'),
       (NOW(), NOW(),
        'public class AddTwoNumbers {\n\tpublic static void main(String[] args) {\n\t\tint num1 = 5;\n\t\tint num2 = 10;\n\t\tint sum = num1 + num2;\n\t\tSystem.out.println("Sum: " + sum);\n\t}\n}',
        'CODE'),
       (NOW(), NOW(),
        'import java.util.Scanner;\n\npublic class UserInput {\n\tpublic static void main(String[] args) {\n\t\tScanner scanner = new Scanner(System.in);\n\t\tSystem.out.print("Enter a number: ");\n\t\tint userInput = scanner.nextInt();\n\t\tSystem.out.println("You entered: " + userInput);\n\t}\n}',
        'CODE'),
       (NOW(), NOW(),
        'public class LoopExample {\n\tpublic static void main(String[] args) {\n\t\tfor (int i = 1; i <= 10; i++) {\n\t\t\tSystem.out.println(i);\n\t\t}\n\t}\n}',
        'CODE'),
       (NOW(), NOW(),
        'import java.util.Scanner;\n\npublic class PositiveNegativeZero {\n\tpublic static void main(String[] args) {\n\t\tScanner scanner = new Scanner(System.in);\n\t\tSystem.out.print("Enter a number: ");\n\t\tint number = scanner.nextInt();\n\n\t\tif (number > 0) {\n\t\t\tSystem.out.println("Positive");\n\t\t} else if (number < 0) {\n\t\t\tSystem.out.println("Negative");\n\t\t} else {\n\t\t\tSystem.out.println("Zero");\n\t\t}\n\t}\n}',
        'CODE'),
       (NOW(), NOW(), 'console.log("Hello, World!");', 'CODE'),
       (NOW(), NOW(), 'let num1 = 5;\nlet num2 = 10;\nlet sum = num1 + num2;\nconsole.log("Sum:", sum);', 'CODE'),
       (NOW(), NOW(), 'let userInput = prompt("Enter a number:");\nconsole.log("You entered:", userInput);', 'CODE'),
       (NOW(), NOW(), 'for (let i = 1; i <= 10; i++) {\n\tconsole.log(i);\n}', 'CODE'),
       (NOW(), NOW(),
        'let number = prompt("Enter a number:");\nif (number > 0) {\n\tconsole.log("Positive");\n} else if (number < 0) {\n\tconsole.log("Negative");\n} else {\n\tconsole.log("Zero");\n}',
        'CODE');


INSERT INTO tikitaza.game_question (created_at, updated_at, question, game_type)
VALUES (NOW(), NOW(), '삶이 있는 한 희망은 있다.', 'SENTENCE'),
       (NOW(), NOW(), '산다는것 그것은 치열한 전투이다.', 'SENTENCE'),
       (NOW(), NOW(), '언제나 현재에 집중할수 있다면 행복할 것이다.', 'SENTENCE'),
       (NOW(), NOW(), '신은 용기있는자를 결코 버리지 않는다.', 'SENTENCE'),
       (NOW(), NOW(), '우리를 향해 열린 문을 보지 못하게 된다.', 'SENTENCE'),
       (NOW(), NOW(), '피할수 없으면 즐겨라.', 'SENTENCE'),
       (NOW(), NOW(), '행복한 삶을 살기위해 필요한 것은 거의 없다.', 'SENTENCE'),
       (NOW(), NOW(), '한번의 실패와 영원한 실패를 혼동하지 마라.', 'SENTENCE'),
       (NOW(), NOW(), '내일은 내일의 태양이 뜬다.', 'SENTENCE'),
       (NOW(), NOW(), '피할수 없으면 즐겨라.', 'SENTENCE'),
       (NOW(), NOW(), '계단을 밟아야 계단 위에 올라설수 있다.', 'SENTENCE'),
       (NOW(), NOW(), '행복은 습관이다, 그것을 몸에 지니라.', 'SENTENCE'),
       (NOW(), NOW(), '자신감 있는 표정을 지으면 자신감이 생긴다.', 'SENTENCE'),
       (NOW(), NOW(), '나이가 성숙을 보장하지는 않는다.', 'SENTENCE'),
       (NOW(), NOW(), '꿈은 내일의 현실이다.', 'SENTENCE'),
       (NOW(), NOW(), '한 사람에게서 모든 덕을 구하지 말라.', 'SENTENCE'),
       (NOW(), NOW(), '개발에 마지막은 없다. 출시만이 있을 뿐이다.', 'SENTENCE'),
       (NOW(), NOW(), '발없는 오픈소스 천리간다.', 'SENTENCE'),
       (NOW(), NOW(), '한 줄 코드라도 서로 거들면 낫다.', 'SENTENCE'),
       (NOW(), NOW(), '아니쓴 코드에 오류날까?', 'SENTENCE'),
       (NOW(), NOW(), '디버깅 한 번으로 천 버그 잡는다.', 'SENTENCE'),
       (NOW(), NOW(), '버그 찾기는 사막에서 바늘찾기', 'SENTENCE'),
       (NOW(), NOW(), '이게 안 되네..? 이게 되네..?', 'SENTENCE');

INSERT INTO game_history (accuracy, wpm, member_id, score, game_type)
VALUES (100, 100, 1, 100, 'WORD'),
       (100, 100, 1, 100, 'CODE'),
       (100, 100, 1, 100, 'WORD'),
       (100, 100, 2, 99, 'SENTENCE'),
       (99, 100, 2, 99, 'WORD');
